### ISSUE TITLE
Release unbranded version of Pro2020 used for TSL

### ISSUE THREAD

**Issue by Peragore** [Ahli/AhliObs-SC2-Mod#11]
TSL9 had the best observer interface we've seen in a while. I would love to use a version of this that doesn't have TSL branding (gummi bears, different fonts, TL unit pane, etc) if possible <3

**Comment by Ahli** [comment]
https://ahli.github.io/Galaxy-Observer-UI/#/pro2020ahlimod/changelog comes close to it, but it is lacking the income numbers. I will probably add them there as well

TSL9 might make the observer interface publicly available. They payed for it, so they can decide what will happen with it 😃
